---
default_language_version:
  python: python3.10

repos:
#  - repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v6.0.0
#    hooks:
#      - id: trailing-whitespace
#      - id: check-merge-conflict
#      - id: mixed-line-ending
#      - id: end-of-file-fixer
#      - id: check-yaml
#      - id: check-toml

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint
